# O nome do nosso robô/workflow. Aparecerá na aba "Actions" do GitHub.
name: CI de Testes Python

# Gatilho: Quando o robô deve trabalhar?
on:
  # A cada 'push' (envio de código) para a branch 'main'.
  push:
    branches: ["main"]
  # Também a cada 'pull request' para a branch 'main'.
  pull_request:
    branches: ["main"]

# Tarefas: A lista de trabalhos que o robô deve executar.
jobs:
  # Nomeamos nosso trabalho de 'build' (construção e teste).
  build:
    # Máquina: O robô vai rodar em uma máquina virtual com Ubuntu (Linux).
    # É o padrão e mais rápido para a maioria dos projetos Python.
    runs-on: ubuntu-latest

    # Passos: A receita exata que o robô deve seguir.
    steps:
      # Passo 1: Baixar o código do nosso "diário" para a máquina virtual.
      - uses: actions/checkout@v3

      # Passo 2: Configurar o ambiente Python na máquina.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Podemos especificar a versão.

      # Passo 3: Instalar todas as ferramentas da nossa lista (requirements.txt).
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Rodar o inspetor de qualidade (pytest).
      - name: Rodar testes com pytest
        run: |
          pytest
